name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

# Allow deploy permissions
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install Dependencies
        run: npm install

      - name: Compile Vite Production Build
        run: node node_modules/vite/bin/vite.js build

      - name: Upload Static Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

      - name: Deploy Static Site
        id: deployment
        uses: actions/deploy-pages@v4
